/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.wijithafc.view.panels;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.wijithaFC.controller.ManageLoginController;
import lk.ijse.wijithafc.common.IDGenerator;
import lk.ijse.wijithafc.dto.LoginDTO;
import lk.ijse.wijithafc.observer.Observer;

/**
 *
 * @author ASUS
 */
public class AdminSettingsPanel extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form AdminSettingsPanel
     */
    public AdminSettingsPanel() {
        initComponents();
        txtAdminCurrentPw.hide();
        lblCurrentPw.hide();
        loadAll();
        try {
            UnicastRemoteObject.exportObject(this,0);
            ManageLoginController.getSubject().registerObserver(this);
        } catch (RemoteException ex) {
            Logger.getLogger(AdminSettingsPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AdminSettingsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdmin = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        txtAdminId = new org.jdesktop.swingx.JXTextField();
        txtAdminName = new org.jdesktop.swingx.JXTextField();
        lblCurrentPw = new org.jdesktop.swingx.JXLabel();
        txtAdminCurrentPw = new javax.swing.JPasswordField();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        txtAdminPw = new javax.swing.JPasswordField();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        txtAddminConPw = new javax.swing.JPasswordField();
        jXButton4 = new org.jdesktop.swingx.JXButton();
        jXButton5 = new org.jdesktop.swingx.JXButton();
        btnADD = new org.jdesktop.swingx.JXButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAdmin = new org.jdesktop.swingx.JXTable();

        setPreferredSize(new java.awt.Dimension(1600, 660));

        pnlAdmin.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdmin.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(204, 204, 204));
        lblAdmin.setText("ADMIN settings");
        pnlAdmin.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 40));

        txtAdminId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAdminId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAdminId.setPrompt("Admin ID");
        pnlAdmin.add(txtAdminId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 370, 40));

        txtAdminName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAdminName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAdminName.setPrompt("Admin Name");
        pnlAdmin.add(txtAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 750, 40));

        lblCurrentPw.setText("Current Password");
        pnlAdmin.add(lblCurrentPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 110, 40));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowColor(new java.awt.Color(51, 102, 255));
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        txtAdminCurrentPw.setBorder(dropShadowBorder1);
        pnlAdmin.add(txtAdminCurrentPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 370, 40));

        jXLabel5.setText("Password");
        pnlAdmin.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 110, 40));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShadowColor(new java.awt.Color(51, 102, 255));
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        txtAdminPw.setBorder(dropShadowBorder2);
        pnlAdmin.add(txtAdminPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 370, 40));

        jXLabel6.setText("Confirm Password");
        pnlAdmin.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 110, 40));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShadowColor(new java.awt.Color(51, 102, 255));
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        txtAddminConPw.setBorder(dropShadowBorder3);
        txtAddminConPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddminConPwActionPerformed(evt);
            }
        });
        pnlAdmin.add(txtAddminConPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 370, 40));

        jXButton4.setBackground(new java.awt.Color(217, 83, 79));
        jXButton4.setForeground(new java.awt.Color(255, 255, 255));
        jXButton4.setText("REMOVE");
        jXButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton4ActionPerformed(evt);
            }
        });
        pnlAdmin.add(jXButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 90, 40));

        jXButton5.setBackground(new java.awt.Color(91, 192, 222));
        jXButton5.setForeground(new java.awt.Color(255, 255, 255));
        jXButton5.setText("EDIT");
        jXButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton5ActionPerformed(evt);
            }
        });
        pnlAdmin.add(jXButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 90, 40));

        btnADD.setBackground(new java.awt.Color(92, 184, 92));
        btnADD.setForeground(new java.awt.Color(255, 255, 255));
        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        pnlAdmin.add(btnADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 90, 40));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShadowColor(new java.awt.Color(204, 0, 204));
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        tblAdmin.setBorder(dropShadowBorder4);
        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admin ID", "Admin Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAdmin);

        pnlAdmin.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 760, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddminConPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddminConPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddminConPwActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        LoginDTO dTO = new LoginDTO(txtAdminId.getText(), "ADMIN", txtAdminName.getText(), txtAdminPw.getText());
        try {
            boolean addLogin = ManageLoginController.addLogin(dTO);
            if (addLogin) {
                JOptionPane.showMessageDialog(null, "Admin Added");
                loadAll();
            } else {
                JOptionPane.showMessageDialog(null, "Added fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(AdminSettingsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void tblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminMouseClicked
        if (tblAdmin.getSelectedRowCount()>0) {
            txtAdminId.setText(tblAdmin.getValueAt(tblAdmin.getSelectedRow(), 0).toString());
            txtAdminName.setText(tblAdmin.getValueAt(tblAdmin.getSelectedRow(), 1).toString());
            lblCurrentPw.show();
            txtAdminCurrentPw.show();
        }
    }//GEN-LAST:event_tblAdminMouseClicked

    private void jXButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton5ActionPerformed
        LoginDTO dTO = new LoginDTO(txtAdminId.getText(), "ADMIN", txtAdminName.getText(), txtAdminPw.getText());
        try {
            boolean addLogin = ManageLoginController.updateLogin(dTO);
            if (addLogin) {
                JOptionPane.showMessageDialog(null, "Admin Updated");
                loadAll();
            } else {
                JOptionPane.showMessageDialog(null, "Update failed");
            }
        } catch (Exception ex) {
            Logger.getLogger(AdminSettingsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXButton5ActionPerformed

    private void jXButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton4ActionPerformed
        LoginDTO dTO = new LoginDTO(txtAdminId.getText(), "ADMIN", txtAdminName.getText(), txtAdminPw.getText());
        try {
            boolean addLogin = ManageLoginController.deleteLogin(dTO);
            if (addLogin) {
                JOptionPane.showMessageDialog(null, "Admin Deleted");
                loadAll();
            } else {
                JOptionPane.showMessageDialog(null, "Delete failed");
            }
        } catch (Exception ex) {
            Logger.getLogger(AdminSettingsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnADD;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXButton jXButton4;
    private org.jdesktop.swingx.JXButton jXButton5;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private javax.swing.JLabel lblAdmin;
    private org.jdesktop.swingx.JXLabel lblCurrentPw;
    private javax.swing.JPanel pnlAdmin;
    private org.jdesktop.swingx.JXTable tblAdmin;
    private javax.swing.JPasswordField txtAddminConPw;
    private javax.swing.JPasswordField txtAdminCurrentPw;
    private org.jdesktop.swingx.JXTextField txtAdminId;
    private org.jdesktop.swingx.JXTextField txtAdminName;
    private javax.swing.JPasswordField txtAdminPw;
    // End of variables declaration//GEN-END:variables
    private void loadAll() {
        DefaultTableModel dtm = (DefaultTableModel) tblAdmin.getModel();
        dtm.setRowCount(0);
        try {
            List<LoginDTO> all = ManageLoginController.getAll();
            if (all != null) {
                for (LoginDTO loginDTO : all) {
                    if (loginDTO.getLoginType().equals("ADMIN")) {
                        Object[] rawData = {loginDTO.getLoginID(), loginDTO.getName()};
                        dtm.addRow(rawData);
                    }
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(UserSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void updateObservers() throws Exception {
        loadAll();
        txtAdminName.setText(null);
        txtAdminId.setText(null);
    }
   
}
