/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.wijithafc.view.panels;

import java.awt.Color;
import javax.swing.JPanel;
import lk.ijse.wijithaFC.view.MainFrame;

/**
 *
 * @author ASUS
 */
public class DashBordItem extends javax.swing.JPanel {

    /**
     * Creates new form SupplierDashBord
     */
    public DashBordItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddItem = new javax.swing.JLabel();
        lblReturnItem = new javax.swing.JLabel();
        lblBatch = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddItem.setBackground(new java.awt.Color(102, 102, 102));
        lblAddItem.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAddItem.setForeground(new java.awt.Color(204, 204, 204));
        lblAddItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddItem.setText("View Item");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowColor(new java.awt.Color(0, 102, 153));
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        lblAddItem.setBorder(dropShadowBorder1);
        lblAddItem.setOpaque(true);
        lblAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddItemMouseClicked(evt);
            }
        });
        add(lblAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        lblReturnItem.setBackground(new java.awt.Color(255, 255, 255));
        lblReturnItem.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblReturnItem.setForeground(new java.awt.Color(204, 204, 204));
        lblReturnItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReturnItem.setText("Return Item");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShadowColor(new java.awt.Color(0, 102, 153));
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        lblReturnItem.setBorder(dropShadowBorder2);
        lblReturnItem.setOpaque(true);
        lblReturnItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReturnItemMouseClicked(evt);
            }
        });
        add(lblReturnItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 240, 40));

        lblBatch.setBackground(new java.awt.Color(255, 255, 255));
        lblBatch.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblBatch.setForeground(new java.awt.Color(204, 204, 204));
        lblBatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBatch.setText("View Batch");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShadowColor(new java.awt.Color(0, 102, 153));
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        lblBatch.setBorder(dropShadowBorder3);
        lblBatch.setOpaque(true);
        lblBatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBatchMouseClicked(evt);
            }
        });
        add(lblBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 240, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItemMouseClicked
        lblAddItem.setBackground(new Color(102, 102, 102));
        lblReturnItem.setBackground(new Color(255, 255, 255));
        lblBatch.setBackground(new Color(255, 255, 255));
        ItemPanel itemPanel = new ItemPanel();
        JPanel pnlMiddle = MainFrame.getMiddlePanel();
        pnlMiddle.removeAll();
        itemPanel.setSize(pnlMiddle.getSize());
        pnlMiddle.add(itemPanel);
        pnlMiddle.revalidate();
        pnlMiddle.repaint();
    }//GEN-LAST:event_lblAddItemMouseClicked

    private void lblReturnItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnItemMouseClicked
        lblReturnItem.setBackground(new Color(102, 102, 102));
        lblAddItem.setBackground(new Color(255, 255, 255));
        lblBatch.setBackground(new Color(255, 255, 255));
        JPanel pnlMid = MainFrame.getMiddlePanel();
        pnlMid.removeAll();
        pnlMid.revalidate();
        pnlMid.repaint();


    }//GEN-LAST:event_lblReturnItemMouseClicked

    private void lblBatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBatchMouseClicked
        lblBatch.setBackground(new Color(102, 102, 102));
        lblAddItem.setBackground(new Color(255, 255, 255));
        lblReturnItem.setBackground(new Color(255, 255, 255));
        JPanel pnlMid = MainFrame.getMiddlePanel();
        ViewBatchPanel batchPanel = new ViewBatchPanel();
        pnlMid.removeAll();
        batchPanel.setSize(pnlMid.getSize());
        pnlMid.add(batchPanel);
        pnlMid.revalidate();
        pnlMid.repaint();
    }//GEN-LAST:event_lblBatchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddItem;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblReturnItem;
    // End of variables declaration//GEN-END:variables
}
