/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.wijithafc.view.panels;

/**
 *
 * @author ASUS
 */
public class DashBordSupplier extends javax.swing.JPanel {

    /**
     * Creates new form SupplierDashBord
     */
    public DashBordSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddApp1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddApp1.setBackground(new java.awt.Color(102, 102, 102));
        lblAddApp1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAddApp1.setForeground(new java.awt.Color(204, 204, 204));
        lblAddApp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddApp1.setText("Supplier Details");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowColor(new java.awt.Color(0, 102, 153));
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        lblAddApp1.setBorder(dropShadowBorder1);
        lblAddApp1.setOpaque(true);
        lblAddApp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddApp1MouseClicked(evt);
            }
        });
        add(lblAddApp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddApp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddApp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAddApp1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddApp1;
    // End of variables declaration//GEN-END:variables
}
