/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.wijithafc.view.panels;

import java.awt.Color;
import javax.swing.JPanel;
import lk.ijse.wijithaFC.view.MainFrame;

/**
 *
 * @author ASUS
 */
public class DashBoardSettings extends javax.swing.JPanel {

    /**
     * Creates new form DashBoardSettinngs
     */
    public DashBoardSettings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdmin = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lblAdmin.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(204, 204, 204));
        lblAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdmin.setText("Admin settings");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowColor(new java.awt.Color(0, 102, 153));
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        lblAdmin.setBorder(dropShadowBorder1);
        lblAdmin.setOpaque(true);
        lblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminMouseClicked(evt);
            }
        });
        add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 240, 40));

        lblUser.setBackground(new java.awt.Color(102, 102, 102));
        lblUser.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("User Settings");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShadowColor(new java.awt.Color(0, 102, 153));
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        lblUser.setBorder(dropShadowBorder2);
        lblUser.setOpaque(true);
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });
        add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void lblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseClicked
        lblAdmin.setBackground(new Color(102, 102, 102));
        lblUser.setBackground(new Color(255, 255, 255));
      
        AdminSettingsPanel settingPanel=new AdminSettingsPanel();
        JPanel middlePanel = MainFrame.getMiddlePanel();
        middlePanel.removeAll();
        settingPanel.setSize(middlePanel.getSize());
        middlePanel.add(settingPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblAdminMouseClicked

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        lblUser.setBackground(new Color(102, 102, 102));
        lblAdmin.setBackground(new Color(255, 255, 255));
        
        UserSettingPanel settingPanel=new UserSettingPanel();
        JPanel middlePanel = MainFrame.getMiddlePanel();
        middlePanel.removeAll();
        settingPanel.setSize(middlePanel.getSize());
        middlePanel.add(settingPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
       
    }//GEN-LAST:event_lblUserMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
