/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.wijithafc.view.panels;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.wijithaFC.controller.ManageItemsController;
import lk.ijse.wijithaFC.controller.ManageSupplierController;
import lk.ijse.wijithaFC.view.DialogFormAddItem;
import lk.ijse.wijithaFC.view.MainFrame;
import lk.ijse.wijithafc.common.IDGenerator;
import lk.ijse.wijithafc.controller.ManageBatchController;
import lk.ijse.wijithafc.controller.ManageGRNController;
import lk.ijse.wijithafc.dto.BatchDTO;
import lk.ijse.wijithafc.dto.GRNDTO;
import lk.ijse.wijithafc.dto.GRNDetailDTO;
import lk.ijse.wijithafc.dto.ItemDTO;
import lk.ijse.wijithafc.dto.SupplierDTO;
import lk.ijse.wijithafc.observer.Observer;
import lk.ijse.wijithafc.view.DialogFormAddNewBatch;

/**
 *
 * @author ASUS
 */
public class GRNPanel extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form GRNPanel
     */
    public GRNPanel() {
        initComponents();
        loadAllSupplier();
        loadAllBatches();
        loadSystemDate();
        loadNewID();

        try {
            UnicastRemoteObject.exportObject(this, 0);
            ManageBatchController.getSubject().registerObserver(this);
            ManageGRNController.getSubject().registerObserver(this);
            ManageSupplierController.getSubject().registerObserver(this);
        } catch (RemoteException ex) {
            Logger.getLogger(GRNPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(GRNPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbCompanyName.requestFocus();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        cmbCompanyName = new org.jdesktop.swingx.JXComboBox();
        txtGRNID = new javax.swing.JTextField();
        btnAddBatch = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        cmbBatch = new org.jdesktop.swingx.JXComboBox();
        jLabel53 = new javax.swing.JLabel();
        txtQtyOld = new javax.swing.JTextField();
        txtQty1 = new javax.swing.JTextField();
        txtSupplierID = new javax.swing.JTextField();
        btnAddNew = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGRNDetail = new org.jdesktop.swingx.JXTable();
        btnRemoveMedicine = new javax.swing.JLabel();
        btnSave = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setText(" Supplier ID   -");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 120, 30));

        jLabel41.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("GRN Details");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText(" GRN NO        -");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 120, 30));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setText(" Date              -");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, 30));

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 260, 30));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText(" Company Name       -");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 160, 30));

        cmbCompanyName.setBorder(null);
        cmbCompanyName.setEditable(true);
        cmbCompanyName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbCompanyName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCompanyNameItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 990, 30));

        txtGRNID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGRNID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtGRNID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGRNIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtGRNID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 260, 30));

        btnAddBatch.setBackground(new java.awt.Color(204, 204, 204));
        btnAddBatch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddBatch.setForeground(new java.awt.Color(255, 255, 255));
        btnAddBatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithaFC/images/add.png"))); // NOI18N
        btnAddBatch.setText("New Batch");
        btnAddBatch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAddBatch.setOpaque(true);
        btnAddBatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddBatchMouseClicked(evt);
            }
        });
        jPanel1.add(btnAddBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, 140, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setText(" Batch            -");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 120, 30));

        cmbBatch.setBorder(null);
        cmbBatch.setEditable(true);
        cmbBatch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbBatch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBatchItemStateChanged(evt);
            }
        });
        cmbBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBatchActionPerformed(evt);
            }
        });
        jPanel1.add(cmbBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 260, 30));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setText(" Quantity                    -");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 160, 30));

        txtQtyOld.setEditable(false);
        txtQtyOld.setBackground(new java.awt.Color(255, 255, 255));
        txtQtyOld.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtQtyOld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowRightShadow(false);
        txtQtyOld.setBorder(dropShadowBorder1);
        txtQtyOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyOldActionPerformed(evt);
            }
        });
        jPanel1.add(txtQtyOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 60, 30));

        txtQty1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtQty1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQty1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQty1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtQty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 100, 30));

        txtSupplierID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSupplierID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSupplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupplierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 260, 30));

        btnAddNew.setBackground(new java.awt.Color(204, 204, 204));
        btnAddNew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNew.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithaFC/images/add.png"))); // NOI18N
        btnAddNew.setText(" New Item");
        btnAddNew.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAddNew.setOpaque(true);
        btnAddNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewMouseClicked(evt);
            }
        });
        jPanel1.add(btnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 150, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 260));

        tblGRNDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch", "ItemCode", "Item Desc", "Unit Cost", "Quantity"
            }
        ));
        tblGRNDetail.setEditable(false);
        tblGRNDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGRNDetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGRNDetail);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1600, 290));

        btnRemoveMedicine.setBackground(new java.awt.Color(102, 102, 102));
        btnRemoveMedicine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemoveMedicine.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveMedicine.setText(" Remove from table");
        btnRemoveMedicine.setOpaque(true);
        btnRemoveMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMedicineMouseClicked(evt);
            }
        });
        add(btnRemoveMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 140, 30));

        btnSave.setBackground(new java.awt.Color(102, 102, 102));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("     Save ");
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 600, 130, 50));

        txtUnitPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUnitPrice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 510, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBatchMouseClicked
        DialogFormAddNewBatch addNewBatch = new DialogFormAddNewBatch(MainFrame.getMainFrame(), true);
        addNewBatch.setVisible(true);
        loadAllBatches();
    }//GEN-LAST:event_btnAddBatchMouseClicked

    private void btnRemoveMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMedicineMouseClicked
        if (tblGRNDetail.getSelectedRowCount() == 1) {
            DefaultTableModel dtm = (DefaultTableModel) tblGRNDetail.getModel();
            dtm.removeRow(tblGRNDetail.getSelectedRow());
        }
    }//GEN-LAST:event_btnRemoveMedicineMouseClicked

    private void cmbCompanyNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCompanyNameItemStateChanged
        if (cmbCompanyName.getSelectedIndex() != -1) {
            try {
                SupplierDTO searchSupplier = ManageSupplierController.searchSupplierByName(cmbCompanyName.getSelectedItem().toString());
                txtSupplierID.setText(searchSupplier.getSupplierID());
            } catch (Exception ex) {
                Logger.getLogger(GRNPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmbCompanyNameItemStateChanged

    private void tblGRNDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGRNDetailMouseClicked

    }//GEN-LAST:event_tblGRNDetailMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        List<GRNDetailDTO> dTOs = new ArrayList<>();
        if (tblGRNDetail.getRowCount() >= 0) {
            for (int i = 0; i < tblGRNDetail.getRowCount(); i++) {
                GRNDetailDTO dTO = new GRNDetailDTO(tblGRNDetail.getValueAt(i, 0).toString(), Double.parseDouble(tblGRNDetail.getValueAt(i, 3).toString()), Integer.parseInt(tblGRNDetail.getValueAt(i, 4).toString()));
                dTOs.add(dTO);
            }
        }
        GRNDTO grndto = new GRNDTO(txtGRNID.getText(), txtDate.getText(), txtSupplierID.getText(), dTOs);
        try {
            boolean addGRN = ManageGRNController.addGRN(grndto);
            if (addGRN) {
                JOptionPane.showMessageDialog(null, "GRN has been added successfully");
                clearFields();
                loadNewID();
                loadAllBatches();

            } else {
                JOptionPane.showMessageDialog(null, "added Fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(GRNPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveMouseClicked

    private void txtGRNIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGRNIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGRNIDActionPerformed

    private void cmbBatchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBatchItemStateChanged

    }//GEN-LAST:event_cmbBatchItemStateChanged

    private void cmbBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBatchActionPerformed
        try {
            if (cmbBatch.getSelectedIndex() != -1) {
                BatchDTO search = ManageBatchController.searchBatch(cmbBatch.getSelectedItem().toString());
                txtQtyOld.setText(Integer.toString(search.getQty()));
            }
        } catch (Exception ex) {
            Logger.getLogger(GRNPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbBatchActionPerformed

    private void txtQtyOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyOldActionPerformed

    }//GEN-LAST:event_txtQtyOldActionPerformed

    private void txtQty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQty1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblGRNDetail.getModel();
        if (cmbBatch.getSelectedIndex() != -1) {
            try {
                BatchDTO searchBatch = ManageBatchController.searchBatch(cmbBatch.getSelectedItem().toString());
                ItemDTO searchItem = ManageItemsController.searchItem(searchBatch.getItemCode());
                Object[] rawData = {cmbBatch.getSelectedItem().toString(), searchBatch.getItemCode(), searchItem.getDescription(), searchBatch.getCost(), Integer.parseInt(txtQty1.getText())};
                dtm.addRow(rawData);
            } catch (Exception ex) {
                Logger.getLogger(GRNPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_txtQty1ActionPerformed

    private void txtSupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierIDActionPerformed
        try {
            SupplierDTO searchSupplier = ManageSupplierController.searchSupplier(txtSupplierID.getText());
            cmbCompanyName.setSelectedItem(searchSupplier.getCompanyName());
        } catch (Exception ex) {
            Logger.getLogger(GRNPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtSupplierIDActionPerformed

    private void btnAddNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseClicked
        DialogFormAddItem addItem = new DialogFormAddItem(MainFrame.getMainFrame(), true);
        addItem.setVisible(true);
    }//GEN-LAST:event_btnAddNewMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddBatch;
    private javax.swing.JLabel btnAddNew;
    private javax.swing.JLabel btnRemoveMedicine;
    private javax.swing.JLabel btnSave;
    private org.jdesktop.swingx.JXComboBox cmbBatch;
    private org.jdesktop.swingx.JXComboBox cmbCompanyName;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable tblGRNDetail;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtGRNID;
    private javax.swing.JTextField txtQty1;
    private javax.swing.JTextField txtQtyOld;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
    private void loadAllSupplier() {

        cmbCompanyName.removeAllItems();
        try {
            List<SupplierDTO> all = ManageSupplierController.getAll();
            if (all != null) {
                for (SupplierDTO supplier : all) {
                    cmbCompanyName.addItem(supplier.getCompanyName());
                }

            }
        } catch (Exception ex) {
            Logger.getLogger(GRNPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllBatches() {
        try {
            List<BatchDTO> all = ManageBatchController.getAll();
            cmbBatch.removeAllItems();
            if (all != null) {
                for (BatchDTO batchDTO : all) {
                    cmbBatch.addItem(batchDTO.getBatchID());

                }
            }
        } catch (Exception ex) {
            Logger.getLogger(GRNPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadSystemDate() {
        Date d1 = new Date(); //Current System date
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formatDate = df.format(d1);
        txtDate.setText(formatDate);

    }

    private void loadNewID() {
        try {
            String lastID = IDGenerator.getLastID(IDGenerator.IdType.GRN);
            txtGRNID.setText(lastID);
        } catch (Exception ex) {
            Logger.getLogger(GRNPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearFields() {
        DefaultTableModel dtm = (DefaultTableModel) tblGRNDetail.getModel();
        dtm.setRowCount(0);
        txtQty1.setText(null);
    }

    @Override
    public void updateObservers() throws Exception {
        loadAllBatches();
        loadAllSupplier();
        loadNewID();
    }
}
