/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.wijithafc.view.panels;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.wijithaFC.controller.ManageLoginController;
import lk.ijse.wijithafc.common.IDGenerator;
import lk.ijse.wijithafc.dto.LoginDTO;
import lk.ijse.wijithafc.observer.Observer;

/**
 *
 * @author ASUS
 */
public class UserSettingPanel extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form UserSettingPanel
     */
    public UserSettingPanel() {
        initComponents();
        txtCurrentPw.hide();
        lblCurrentPw.hide();
        loadAll();
        try {
            UnicastRemoteObject.exportObject(this, 0);
            ManageLoginController.getSubject().registerObserver(this);
        } catch (RemoteException ex) {
            Logger.getLogger(UserSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(UserSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser = new javax.swing.JPanel();
        txtUserName = new org.jdesktop.swingx.JXTextField();
        txtUserID = new org.jdesktop.swingx.JXTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new org.jdesktop.swingx.JXTable();
        lblUser = new javax.swing.JLabel();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        jXButton2 = new org.jdesktop.swingx.JXButton();
        jXButton3 = new org.jdesktop.swingx.JXButton();
        txtConfirm = new javax.swing.JPasswordField();
        txtCurrentPw = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        lblCurrentPw = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();

        setPreferredSize(new java.awt.Dimension(1600, 660));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUserName.setPrompt("User Name");
        pnlUser.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 750, 40));

        txtUserID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUserID.setPrompt("User ID");
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });
        pnlUser.add(txtUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 370, 40));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowColor(new java.awt.Color(204, 0, 204));
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        tblUser.setBorder(dropShadowBorder1);
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "User Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        pnlUser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 760, 630));

        lblUser.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setText("USER settings");
        pnlUser.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 40));

        jXButton1.setBackground(new java.awt.Color(92, 184, 92));
        jXButton1.setForeground(new java.awt.Color(255, 255, 255));
        jXButton1.setText("ADD");
        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });
        pnlUser.add(jXButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 90, 40));

        jXButton2.setBackground(new java.awt.Color(91, 192, 222));
        jXButton2.setForeground(new java.awt.Color(255, 255, 255));
        jXButton2.setText("EDIT");
        jXButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton2ActionPerformed(evt);
            }
        });
        pnlUser.add(jXButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 90, 40));

        jXButton3.setBackground(new java.awt.Color(217, 83, 79));
        jXButton3.setForeground(new java.awt.Color(255, 255, 255));
        jXButton3.setText("REMOVE");
        jXButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton3ActionPerformed(evt);
            }
        });
        pnlUser.add(jXButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 90, 40));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShadowColor(new java.awt.Color(51, 102, 255));
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        txtConfirm.setBorder(dropShadowBorder2);
        pnlUser.add(txtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 370, 40));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShadowColor(new java.awt.Color(51, 102, 255));
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        txtCurrentPw.setBorder(dropShadowBorder3);
        pnlUser.add(txtCurrentPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 370, 40));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShadowColor(new java.awt.Color(51, 102, 255));
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        txtPassword.setBorder(dropShadowBorder4);
        pnlUser.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 370, 40));

        lblCurrentPw.setText("Current Password");
        pnlUser.add(lblCurrentPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 110, 40));

        jXLabel2.setText("Password");
        pnlUser.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 110, 40));

        jXLabel3.setText("Confirm Password");
        pnlUser.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        if (tblUser.getSelectedRowCount() > 0) {
            txtUserID.setText(tblUser.getValueAt(tblUser.getSelectedRow(), 0).toString());
            txtUserName.setText(tblUser.getValueAt(tblUser.getSelectedRow(), 1).toString());
            lblCurrentPw.show();
            txtCurrentPw.show();
        }
    }//GEN-LAST:event_tblUserMouseClicked

    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
        LoginDTO dTO = new LoginDTO(txtUserID.getText(), "USER", txtUserName.getText(), txtPassword.getText());
        try {
            boolean addLogin = ManageLoginController.addLogin(dTO);
            if (addLogin) {
                JOptionPane.showMessageDialog(null, "User Added");
                loadAll();
            } else {
                JOptionPane.showMessageDialog(null, "failed");
            }
        } catch (Exception ex) {
            Logger.getLogger(UserSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXButton1ActionPerformed

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIDActionPerformed

    private void jXButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton2ActionPerformed
        LoginDTO dTO = new LoginDTO(txtUserID.getText(), "USER", txtUserName.getText(), txtPassword.getText());
        try {
            boolean addLogin = ManageLoginController.updateLogin(dTO);
            if (addLogin) {
                JOptionPane.showMessageDialog(null, "User Updated");
                loadAll();
                txtPassword.setText(null);
                txtCurrentPw.setText(null);
                txtConfirm.setText(null);
                txtUserID.setText(null);
                txtUserName.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, "failed");
            }
        } catch (Exception ex) {
            Logger.getLogger(UserSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXButton2ActionPerformed

    private void jXButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton3ActionPerformed
        LoginDTO dTO = new LoginDTO(txtUserID.getText(), "USER", txtUserName.getText(), txtPassword.getText());
        try {
            boolean addLogin = ManageLoginController.deleteLogin(dTO);
            if (addLogin) {
                JOptionPane.showMessageDialog(null, "User Deleted");
                loadAll();
                txtPassword.setText(null);
                txtCurrentPw.setText(null);
                txtConfirm.setText(null);
                txtUserID.setText(null);
                txtUserName.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, "failed");
            }
        } catch (Exception ex) {
            Logger.getLogger(UserSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXButton jXButton2;
    private org.jdesktop.swingx.JXButton jXButton3;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel lblCurrentPw;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlUser;
    private org.jdesktop.swingx.JXTable tblUser;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JPasswordField txtCurrentPw;
    private javax.swing.JPasswordField txtPassword;
    private org.jdesktop.swingx.JXTextField txtUserID;
    private org.jdesktop.swingx.JXTextField txtUserName;
    // End of variables declaration//GEN-END:variables
    private void loadAll() {
        DefaultTableModel dtm = (DefaultTableModel) tblUser.getModel();
        dtm.setRowCount(0);
        try {
            List<LoginDTO> all = ManageLoginController.getAll();
            if (all != null) {
                for (LoginDTO loginDTO : all) {
                    if (loginDTO.getLoginType().equals("USER")) {
                        Object[] rawData = {loginDTO.getLoginID(), loginDTO.getName()};
                        dtm.addRow(rawData);
                    }
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(UserSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void updateObservers() throws Exception {
        loadAll();
        txtUserID.setText(null);
        txtUserName.setText(null);
    }

  
}
