/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.wijithafc.view.panels;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.wijithaFC.controller.ManageItemsController;
import lk.ijse.wijithafc.controller.ManageBatchController;
import lk.ijse.wijithafc.dto.BatchDTO;
import lk.ijse.wijithafc.dto.ItemDTO;
import lk.ijse.wijithafc.observer.Observer;

/**
 *
 * @author ASUS
 */
public class ViewBatchPanel extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form viewBatchPanel
     */
    public ViewBatchPanel() {
        initComponents();
        loadAllBatches();
        try {
            UnicastRemoteObject.exportObject(this, 0);
             ManageBatchController.getSubject().registerObserver(this);
        } catch (RemoteException ex) {
            Logger.getLogger(ViewBatchPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ViewBatchPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBatchID = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtDate = new org.jdesktop.swingx.JXDatePicker();
        lblUser = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        btnRemove = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBatches = new org.jdesktop.swingx.JXTable();
        txtItemCode = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBatchID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBatchID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtBatchID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBatchIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBatchIDFocusLost(evt);
            }
        });
        txtBatchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatchIDActionPerformed(evt);
            }
        });
        add(txtBatchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 220, 30));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 51, 51));
        jLabel45.setText("Batch ID      -");
        add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 110, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("ItemCode    -");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 110, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Unit Cost     -");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 110, 30));

        txtCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCost.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCostFocusLost(evt);
            }
        });
        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });
        add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 220, 30));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 51, 51));
        jLabel46.setText("Expire Date-");
        add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 110, 30));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 220, 30));

        lblUser.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setText("View Batch");
        add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        btnEdit.setBackground(new java.awt.Color(102, 102, 102));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("      Edit ");
        btnEdit.setOpaque(true);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 590, 130, 50));

        btnRemove.setBackground(new java.awt.Color(102, 102, 102));
        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(189, 103, 107));
        btnRemove.setText("  Remove");
        btnRemove.setOpaque(true);
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 590, 130, 50));

        tblBatches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch ID", "ItemCode", "Item Description", "Unit cost", "Qty", "Expire Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBatches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBatchesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBatches);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1600, 300));

        txtItemCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtItemCode.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtItemCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemCodeFocusLost(evt);
            }
        });
        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });
        add(txtItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 220, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Qty              -");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 110, 30));

        txtQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQty.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtyFocusLost(evt);
            }
        });
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 220, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBatchIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBatchIDFocusGained

    }//GEN-LAST:event_txtBatchIDFocusGained

    private void txtBatchIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBatchIDFocusLost

    }//GEN-LAST:event_txtBatchIDFocusLost

    private void txtBatchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatchIDActionPerformed

    }//GEN-LAST:event_txtBatchIDActionPerformed

    private void txtCostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCostFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostFocusGained

    private void txtCostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCostFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostFocusLost

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        BatchDTO dto=new BatchDTO(txtBatchID.getText(),txtItemCode.getText(), Integer.parseInt(txtQty.getText()), Double.parseDouble(txtCost.getText()),convertDate(txtDate.getDate()));
        try {
            boolean updateBatch = ManageBatchController.updateBatch(dto);
            if(updateBatch){
                JOptionPane.showMessageDialog(null,"Batch has been updated successfully");
                loadAllBatches();
                clearFiels();
            }else{
                 JOptionPane.showMessageDialog(null,"Failed");
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewBatchPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked
         BatchDTO dto=new BatchDTO(txtBatchID.getText(),txtItemCode.getText(), Integer.parseInt(txtQty.getText()), Double.parseDouble(txtCost.getText()),convertDate(txtDate.getDate()));
        try {
            boolean delete = ManageBatchController.deleteBatch(dto);
            if(delete){
                JOptionPane.showMessageDialog(null,"Batch has been Deleted successfully");
                loadAllBatches();
                clearFiels();
            }else{
                 JOptionPane.showMessageDialog(null,"Failed");
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewBatchPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoveMouseClicked

    private void txtItemCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemCodeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCodeFocusGained

    private void txtItemCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemCodeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCodeFocusLost

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void txtQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyFocusGained

    private void txtQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyFocusLost

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void tblBatchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBatchesMouseClicked
      if(tblBatches.getSelectedRowCount()!=-1){
          txtBatchID.setText(tblBatches.getValueAt(tblBatches.getSelectedRow(),0).toString());
          txtCost.setText(tblBatches.getValueAt(tblBatches.getSelectedRow(),3).toString());
          txtDate.setDate(convertStringToDate(tblBatches.getValueAt(tblBatches.getSelectedRow(), 5).toString()));
          txtItemCode.setText(tblBatches.getValueAt(tblBatches.getSelectedRow(),1).toString());
          txtQty.setText(tblBatches.getValueAt(tblBatches.getSelectedRow(), 4).toString());
          
      }
    }//GEN-LAST:event_tblBatchesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnRemove;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUser;
    private org.jdesktop.swingx.JXTable tblBatches;
    private javax.swing.JTextField txtBatchID;
    private javax.swing.JTextField txtCost;
    private org.jdesktop.swingx.JXDatePicker txtDate;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
private void loadAllBatches() {
        DefaultTableModel dtm = (DefaultTableModel)tblBatches.getModel();
    try {
            List<BatchDTO> all = ManageBatchController.getAll();
            dtm.setRowCount(0);
            if (all != null) {
                for (BatchDTO batchDTO : all) {
                    ItemDTO searchItem = ManageItemsController.searchItem(batchDTO.getItemCode());
                    Object[] rawData={batchDTO.getBatchID(),batchDTO.getItemCode(),searchItem.getDescription(),batchDTO.getCost(),batchDTO.getQty(),batchDTO.getExpireDate()};
                    dtm.addRow(rawData);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewBatchPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
 public String convertDate(Date date) {
        SimpleDateFormat sdfr = new SimpleDateFormat("dd/MMM/yyyy");
        String dateString = sdfr.format(date);
        return dateString;
    }
 public Date convertStringToDate(String date) {
        SimpleDateFormat sdfr = new SimpleDateFormat("dd/MMM/yyyy");
        try {
            Date parse = sdfr.parse(date);
            return parse;
        } catch (ParseException ex) {
            Logger.getLogger(ViewBatchPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    @Override
    public void updateObservers() throws Exception {
       loadAllBatches();
    }
    private void clearFiels(){
        txtBatchID.setText(null);
        txtCost.setText(null);
        txtDate.setDate(null);
        txtItemCode.setText(null);
        txtQty.setText(null);
    }
}
