/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.wijithaFC.view;

import java.awt.Color;
import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.wijithaFC.controller.ManageItemsController;
import lk.ijse.wijithafc.common.IDGenerator;
import lk.ijse.wijithafc.controller.CategoryController;
import lk.ijse.wijithafc.dto.CategoryDTO;
import lk.ijse.wijithafc.dto.ItemDTO;
import lk.ijse.wijithafc.observer.Observer;

/**
 *
 * @author ASUS
 */
public class DialogFormAddItem extends javax.swing.JDialog implements Observer {

    /**
     * Creates new form AddOwner
     */
    public DialogFormAddItem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadNewID();
        loadCat();
        try {
            UnicastRemoteObject.exportObject(this, 0);
            ManageItemsController.getSubject().registerObserver(this);
        } catch (RemoteException ex) {
            Logger.getLogger(DialogFormAddItem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(DialogFormAddItem.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtdesc.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtUnitprice = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtdesc = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        btnAda = new javax.swing.JLabel();
        txtQtyOnHand = new javax.swing.JTextField();
        btnCancel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbCategory = new org.jdesktop.swingx.JXComboBox();
        txtDiscount = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDiscountQty = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        btnAddNew2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel8.setBackground(new java.awt.Color(250, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 135, 173), 5));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(29, 120, 156));
        jLabel41.setText("Add New Item");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(40, 135, 173));
        jLabel27.setText("ItemCode    -");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 30));

        txtCode.setBackground(new java.awt.Color(250, 255, 255));
        txtCode.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtCode.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 220, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(40, 135, 173));
        jLabel15.setText("Category       -");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        txtUnitprice.setBackground(new java.awt.Color(250, 255, 255));
        txtUnitprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUnitprice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUnitprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitpriceActionPerformed(evt);
            }
        });
        jPanel8.add(txtUnitprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 220, 30));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(40, 135, 173));
        jLabel45.setText("Description -");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 30));

        txtdesc.setBackground(new java.awt.Color(250, 255, 255));
        txtdesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdesc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescActionPerformed(evt);
            }
        });
        jPanel8.add(txtdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 940, 30));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(40, 135, 173));
        jLabel46.setText("Qty OnHand-");
        jPanel8.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, 30));

        btnAda.setBackground(new java.awt.Color(102, 102, 102));
        btnAda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAda.setForeground(new java.awt.Color(255, 255, 255));
        btnAda.setText("+ New Item");
        btnAda.setOpaque(true);
        btnAda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdaMouseClicked(evt);
            }
        });
        jPanel8.add(btnAda, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 130, 50));

        txtQtyOnHand.setBackground(new java.awt.Color(250, 255, 255));
        txtQtyOnHand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQtyOnHand.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQtyOnHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyOnHandActionPerformed(evt);
            }
        });
        jPanel8.add(txtQtyOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 220, 30));

        btnCancel.setBackground(new java.awt.Color(217, 83, 79));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("       Cancel");
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
        });
        jPanel8.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 130, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(40, 135, 173));
        jLabel14.setText("UnitPrice      -");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 30));

        cmbCategory.setBackground(new java.awt.Color(250, 255, 255));
        cmbCategory.setEditable(true);
        cmbCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });
        jPanel8.add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 220, 30));

        txtDiscount.setBackground(new java.awt.Color(250, 255, 255));
        txtDiscount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiscount.setText("0");
        txtDiscount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 220, 30));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(40, 135, 173));
        jLabel47.setText("Discount        -");
        jPanel8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 110, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(40, 135, 173));
        jLabel16.setText("Discount Qty -");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 110, 30));

        txtDiscountQty.setBackground(new java.awt.Color(250, 255, 255));
        txtDiscountQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiscountQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiscountQty.setText("0");
        txtDiscountQty.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDiscountQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountQtyActionPerformed(evt);
            }
        });
        jPanel8.add(txtDiscountQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 220, 30));

        jPanel1.setBackground(new java.awt.Color(250, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDelete.setOpaque(true);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 100, 30));

        txtCategory.setBackground(new java.awt.Color(250, 255, 255));
        txtCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 220, 30));

        btnAddNew2.setBackground(new java.awt.Color(204, 204, 204));
        btnAddNew2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddNew2.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNew2.setText("ADD Category");
        btnAddNew2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAddNew2.setOpaque(true);
        btnAddNew2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNew2MouseClicked(evt);
            }
        });
        jPanel1.add(btnAddNew2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, 30));

        jPanel8.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 320, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdaMouseClicked
        try {

            ItemDTO dTO = new ItemDTO(txtCode.getText(), txtdesc.getText(), cmbCategory.getSelectedItem().toString(), Double.parseDouble(txtUnitprice.getText()), Integer.parseInt(txtQtyOnHand.getText()), Integer.parseInt(txtDiscountQty.getText()), Double.parseDouble(txtDiscount.getText()));
            boolean addItem = ManageItemsController.addItem(dTO);
            if (addItem) {
                JOptionPane.showMessageDialog(null, "Item has been added successfully");
                this.dispose();
                ManageItemsController.releaseItem(txtCode.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Failed");
            }

        } catch (Exception ex) {
            Logger.getLogger(DialogFormAddItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdaMouseClicked

    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        btnCancel.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_btnCancelMousePressed

    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        btnCancel.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnCancelMouseReleased

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void txtdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescActionPerformed
        cmbCategory.requestFocus();
    }//GEN-LAST:event_txtdescActionPerformed

    private void txtUnitpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitpriceActionPerformed
        txtQtyOnHand.requestFocus();
    }//GEN-LAST:event_txtUnitpriceActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        txtUnitprice.requestFocus();
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void txtDiscountQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountQtyActionPerformed
        txtDiscount.requestFocus();
    }//GEN-LAST:event_txtDiscountQtyActionPerformed

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        try {
            List<CategoryDTO> all = CategoryController.getAll();
            if (all != null) {
                for (CategoryDTO categoryDTO : all) {
                    if (categoryDTO.getCategory().equals(txtCategory.getText())) {
                        boolean deleteCat = CategoryController.deleteCat(categoryDTO);
                        if (deleteCat) {
                            JOptionPane.showMessageDialog(rootPane, "deleted");
                            loadCat();
                            txtCategory.setText(null);
                        }
                    }

                }
            }
        } catch (Exception ex) {
            Logger.getLogger(DialogFormAddItem.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnAddNew2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNew2MouseClicked
        addCat();
        loadCat();
        txtCategory.setText(null);
    }//GEN-LAST:event_btnAddNew2MouseClicked

    private void txtQtyOnHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyOnHandActionPerformed
        txtDiscountQty.requestFocus();
    }//GEN-LAST:event_txtQtyOnHandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogFormAddItem dialog = new DialogFormAddItem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAda;
    private javax.swing.JLabel btnAddNew2;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnDelete;
    private org.jdesktop.swingx.JXComboBox cmbCategory;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtDiscountQty;
    private javax.swing.JTextField txtQtyOnHand;
    private javax.swing.JTextField txtUnitprice;
    private javax.swing.JTextField txtdesc;
    // End of variables declaration//GEN-END:variables

    private void loadNewID() {
        try {
            String lastID = IDGenerator.getLastID(IDGenerator.IdType.ITEM);
            txtCode.setText(lastID);
        } catch (Exception ex) {
            Logger.getLogger(DialogFormAddItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void updateObservers() throws Exception {
        loadNewID();
    }

    private void loadCat() {
        cmbCategory.removeAllItems();
        try {
            List<CategoryDTO> all = CategoryController.getAll();
            if (all != null) {
                for (CategoryDTO categoryDTO : all) {
                    cmbCategory.addItem(categoryDTO.getCategory());
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(DialogFormAddItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void addCat() {
        CategoryDTO categoryDTO = new CategoryDTO();
        categoryDTO.setCategory(txtCategory.getText());
        try {
            boolean addCat = CategoryController.addCat(categoryDTO);
            if (addCat) {
                JOptionPane.showMessageDialog(rootPane, "Added");
            }
        } catch (Exception ex) {
            Logger.getLogger(DialogFormAddItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
