/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.wijithaFC.view;

import lk.ijse.wijithafc.view.panels.UserSettingPanel;
import lk.ijse.wijithafc.view.panels.DashBoardSettings;
import lk.ijse.wijithafc.view.panels.DashBoardGRN;
import lk.ijse.wijithafc.view.panels.DashBordSupplier;
import lk.ijse.wijithafc.view.panels.SupplierPanel;
import lk.ijse.wijithafc.view.panels.ItemPanel;
import lk.ijse.wijithafc.view.panels.GRNPanel;
import lk.ijse.wijithafc.view.panels.DashBordItem;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lk.ijse.wijithafc.view.DialogFormAdminLogin;
import lk.ijse.wijithafc.view.panels.CashierPanel;
import lk.ijse.wijithafc.view.LoginForm;
import lk.ijse.wijithafc.view.panels.ReportPanel;

/**
 *
 * @author ASUS
 */
public class MainFrame extends javax.swing.JFrame {

    private static JFrame homeFrame;
    private static String userID;
    private static String userType;
    private boolean isAdminLogged = false;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        homeFrame = this;

    }

    public MainFrame(String userID, String userType) {
        this();
        MainFrame.userID = userID;
        txtUserID.setText(userID);
        this.userType = userType;
        enableFields(userType);
        lblCashierMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        lblLogOut = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        pnlMiddle = new javax.swing.JPanel();
        pnlItem = new javax.swing.JPanel();
        lblItem = new javax.swing.JLabel();
        pnlSupplier = new javax.swing.JPanel();
        lblSupplier = new javax.swing.JLabel();
        pnlGRN = new javax.swing.JPanel();
        lblGRN = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        pnlSettings = new javax.swing.JPanel();
        lblReports = new javax.swing.JLabel();
        pnlReports = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        lblCancel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCashier = new javax.swing.JLabel();
        pnlCashier = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setMinimumSize(new java.awt.Dimension(1580, 850));
        jPanel10.setPreferredSize(new java.awt.Dimension(1580, 920));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 65)); // NOI18N
        jLabel30.setText("Wijitha Food City");
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 700, 120));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel56.setText(" User ID   -  ");
        jPanel13.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 170, 120, 40));

        txtUserID.setEditable(false);
        txtUserID.setBackground(new java.awt.Color(255, 255, 255));
        txtUserID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtUserID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(txtUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 170, 160, 40));

        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithafc/images/logout1.png"))); // NOI18N
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
        });
        jPanel13.add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 90, 70, 70));

        lblAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithafc/images/Admin.png"))); // NOI18N
        jPanel13.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 90, 60, 70));

        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 1600, 210));

        pnlMiddle.setBackground(new java.awt.Color(255, 255, 255));
        pnlMiddle.setForeground(new java.awt.Color(255, 255, 255));
        pnlMiddle.setLayout(new java.awt.CardLayout());
        jPanel10.add(pnlMiddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 1600, 660));

        javax.swing.GroupLayout pnlItemLayout = new javax.swing.GroupLayout(pnlItem);
        pnlItem.setLayout(pnlItemLayout);
        pnlItemLayout.setHorizontalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlItemLayout.setVerticalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel10.add(pnlItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 434, 10, 100));

        lblItem.setBackground(new java.awt.Color(0, 102, 102));
        lblItem.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblItem.setForeground(new java.awt.Color(255, 255, 255));
        lblItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithaFC/images/trolley.png"))); // NOI18N
        lblItem.setText("    Item");
        lblItem.setOpaque(true);
        lblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblItemMouseEntered(evt);
            }
        });
        jPanel10.add(lblItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 434, 240, 100));

        javax.swing.GroupLayout pnlSupplierLayout = new javax.swing.GroupLayout(pnlSupplier);
        pnlSupplier.setLayout(pnlSupplierLayout);
        pnlSupplierLayout.setHorizontalGroup(
            pnlSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlSupplierLayout.setVerticalGroup(
            pnlSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel10.add(pnlSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 546, 10, 100));

        lblSupplier.setBackground(new java.awt.Color(0, 102, 102));
        lblSupplier.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblSupplier.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithaFC/images/lorry.png"))); // NOI18N
        lblSupplier.setText(" Supplier");
        lblSupplier.setOpaque(true);
        lblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupplierMouseEntered(evt);
            }
        });
        jPanel10.add(lblSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 546, 240, 100));

        javax.swing.GroupLayout pnlGRNLayout = new javax.swing.GroupLayout(pnlGRN);
        pnlGRN.setLayout(pnlGRNLayout);
        pnlGRNLayout.setHorizontalGroup(
            pnlGRNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlGRNLayout.setVerticalGroup(
            pnlGRNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel10.add(pnlGRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 658, 10, 100));

        lblGRN.setBackground(new java.awt.Color(0, 102, 102));
        lblGRN.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblGRN.setForeground(new java.awt.Color(255, 255, 255));
        lblGRN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGRN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithaFC/images/GRN.png"))); // NOI18N
        lblGRN.setText("   GRN");
        lblGRN.setOpaque(true);
        lblGRN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGRNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGRNMouseEntered(evt);
            }
        });
        jPanel10.add(lblGRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 658, 240, 100));

        lblSettings.setBackground(new java.awt.Color(0, 102, 102));
        lblSettings.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblSettings.setForeground(new java.awt.Color(255, 255, 255));
        lblSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithaFC/images/settings.png"))); // NOI18N
        lblSettings.setText(" Setting");
        lblSettings.setOpaque(true);
        lblSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSettingsMouseEntered(evt);
            }
        });
        jPanel10.add(lblSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 770, 240, 100));

        javax.swing.GroupLayout pnlSettingsLayout = new javax.swing.GroupLayout(pnlSettings);
        pnlSettings.setLayout(pnlSettingsLayout);
        pnlSettingsLayout.setHorizontalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlSettingsLayout.setVerticalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel10.add(pnlSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 770, 10, 100));

        lblReports.setBackground(new java.awt.Color(0, 102, 102));
        lblReports.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblReports.setForeground(new java.awt.Color(255, 255, 255));
        lblReports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithaFC/images/report.png"))); // NOI18N
        lblReports.setText("Reports");
        lblReports.setOpaque(true);
        lblReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportsMouseEntered(evt);
            }
        });
        jPanel10.add(lblReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 882, 240, 100));

        javax.swing.GroupLayout pnlReportsLayout = new javax.swing.GroupLayout(pnlReports);
        pnlReports.setLayout(pnlReportsLayout);
        pnlReportsLayout.setHorizontalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlReportsLayout.setVerticalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel10.add(pnlReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 882, 10, 100));

        pnlDashboard.setBackground(new java.awt.Color(255, 255, 255));
        pnlDashboard.setLayout(new java.awt.CardLayout());
        jPanel10.add(pnlDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 250, 1600, 40));

        lblCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithaFC/images/x-mark (2).png"))); // NOI18N
        lblCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelMouseExited(evt);
            }
        });
        jPanel10.add(lblCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1880, 0, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithaFC/images/minimize.png"))); // NOI18N
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithafc/images/3.png"))); // NOI18N
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 270));

        lblCashier.setBackground(new java.awt.Color(0, 102, 102));
        lblCashier.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblCashier.setForeground(new java.awt.Color(255, 255, 255));
        lblCashier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/wijithaFC/images/cashier.png"))); // NOI18N
        lblCashier.setText("Cashier");
        lblCashier.setOpaque(true);
        lblCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCashierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCashierMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCashierMousePressed(evt);
            }
        });
        jPanel10.add(lblCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 322, 240, 100));

        javax.swing.GroupLayout pnlCashierLayout = new javax.swing.GroupLayout(pnlCashier);
        pnlCashier.setLayout(pnlCashierLayout);
        pnlCashierLayout.setHorizontalGroup(
            pnlCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlCashierLayout.setVerticalGroup(
            pnlCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel10.add(pnlCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 322, 10, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1914, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered

    }//GEN-LAST:event_jPanel13MouseEntered

    private void lblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemMouseClicked
        if (lblItem.isEnabled()) {
            setPanelColour(pnlItem);
            resetPanelColour(pnlGRN, pnlSettings, pnlSupplier, pnlReports, pnlCashier);
            ItemPanel itemPanel = new ItemPanel();
            this.pnlMiddle.removeAll();
            itemPanel.setSize(this.pnlMiddle.getSize());
            pnlMiddle.add(itemPanel);
            pnlMiddle.revalidate();
            pnlMiddle.repaint();

            DashBordItem dItem = new DashBordItem();
            this.pnlDashboard.removeAll();
            dItem.setSize(this.pnlDashboard.getSize());
            pnlDashboard.add(dItem);
            pnlDashboard.revalidate();
            pnlDashboard.repaint();
        } else {
            DialogFormAdminLogin adminLogin = new lk.ijse.wijithafc.view.DialogFormAdminLogin(this, true);
            adminLogin.setVisible(true);
            if (adminLogin.isLoged()) {
                enableFields("ADMIN");
                setPanelColour(pnlItem);
                resetPanelColour(pnlGRN, pnlSettings, pnlSupplier, pnlReports, pnlCashier);
                ItemPanel itemPanel = new ItemPanel();
                this.pnlMiddle.removeAll();
                itemPanel.setSize(this.pnlMiddle.getSize());
                pnlMiddle.add(itemPanel);
                pnlMiddle.revalidate();
                pnlMiddle.repaint();

                DashBordItem dItem = new DashBordItem();
                this.pnlDashboard.removeAll();
                dItem.setSize(this.pnlDashboard.getSize());
                pnlDashboard.add(dItem);
                pnlDashboard.revalidate();
                pnlDashboard.repaint();
            }
        }

    }//GEN-LAST:event_lblItemMouseClicked

    private void lblItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemMouseEntered
        lblItem.setBackground(new Color(69, 108, 123));
    }//GEN-LAST:event_lblItemMouseEntered

    private void lblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseClicked
        if (lblSupplier.isEnabled()) {
            setPanelColour(pnlSupplier);
            resetPanelColour(pnlItem, pnlSettings, pnlGRN, pnlReports, pnlCashier);
            SupplierPanel sp = new SupplierPanel();
            this.pnlMiddle.removeAll();
            sp.setSize(this.pnlMiddle.getSize());
            pnlMiddle.add(sp);
            pnlMiddle.revalidate();
            pnlMiddle.repaint();

            DashBordSupplier dsp = new DashBordSupplier();
            this.pnlDashboard.removeAll();
            dsp.setSize(this.pnlDashboard.getSize());
            pnlDashboard.add(dsp);
            pnlDashboard.revalidate();
            pnlDashboard.repaint();
        } else {
            DialogFormAdminLogin adminLogin = new lk.ijse.wijithafc.view.DialogFormAdminLogin(this, true);
            adminLogin.setVisible(true);
            if (adminLogin.isLoged()) {
                enableFields("ADMIN");
                setPanelColour(pnlSupplier);
                resetPanelColour(pnlItem, pnlSettings, pnlGRN, pnlReports, pnlCashier);
                SupplierPanel sp = new SupplierPanel();
                this.pnlMiddle.removeAll();
                sp.setSize(this.pnlMiddle.getSize());
                pnlMiddle.add(sp);
                pnlMiddle.revalidate();
                pnlMiddle.repaint();

                DashBordSupplier dsp = new DashBordSupplier();
                this.pnlDashboard.removeAll();
                dsp.setSize(this.pnlDashboard.getSize());
                pnlDashboard.add(dsp);
                pnlDashboard.revalidate();
                pnlDashboard.repaint();
            }
        }
    }//GEN-LAST:event_lblSupplierMouseClicked

    private void lblSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseEntered
        lblSupplier.setBackground(new Color(69, 108, 123));
    }//GEN-LAST:event_lblSupplierMouseEntered

    private void lblGRNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGRNMouseClicked
        if (lblGRN.isEnabled()) {
            setPanelColour(pnlGRN);
            resetPanelColour(pnlItem, pnlSettings, pnlSupplier, pnlReports, pnlCashier);
            GRNPanel panel = new GRNPanel();
            this.pnlMiddle.removeAll();
            panel.setSize(this.pnlMiddle.getSize());
            pnlMiddle.add(panel);
            pnlMiddle.revalidate();
            pnlMiddle.repaint();

            DashBoardGRN boardGRN = new DashBoardGRN();
            this.pnlDashboard.removeAll();
            boardGRN.setSize(this.pnlDashboard.getSize());
            pnlDashboard.add(boardGRN);
            pnlDashboard.revalidate();
            pnlDashboard.repaint();
        } else {
            DialogFormAdminLogin adminLogin = new lk.ijse.wijithafc.view.DialogFormAdminLogin(this, true);
            adminLogin.setVisible(true);
            if (adminLogin.isLoged()) {
                enableFields("ADMIN");
                setPanelColour(pnlGRN);
                resetPanelColour(pnlItem, pnlSettings, pnlSupplier, pnlReports, pnlCashier);
                GRNPanel panel = new GRNPanel();
                this.pnlMiddle.removeAll();
                panel.setSize(this.pnlMiddle.getSize());
                pnlMiddle.add(panel);
                pnlMiddle.revalidate();
                pnlMiddle.repaint();

                DashBoardGRN boardGRN = new DashBoardGRN();
                this.pnlDashboard.removeAll();
                boardGRN.setSize(this.pnlDashboard.getSize());
                pnlDashboard.add(boardGRN);
                pnlDashboard.revalidate();
                pnlDashboard.repaint();
            }
        }
    }//GEN-LAST:event_lblGRNMouseClicked

    private void lblGRNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGRNMouseEntered
        lblGRN.setBackground(new Color(69, 108, 123));
    }//GEN-LAST:event_lblGRNMouseEntered

    private void lblSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseClicked
        setPanelColour(pnlSettings);
        resetPanelColour(pnlSupplier, pnlGRN, pnlReports, pnlItem, pnlCashier);
        UserSettingPanel panel = new UserSettingPanel();
        this.pnlMiddle.removeAll();
        panel.setSize(pnlMiddle.getSize());
        pnlMiddle.add(panel);
        pnlMiddle.revalidate();
        pnlMiddle.repaint();

        DashBoardSettings dbs = new DashBoardSettings();
        this.pnlDashboard.removeAll();
        dbs.setSize(this.pnlDashboard.getSize());
        pnlDashboard.add(dbs);
        pnlDashboard.revalidate();
        pnlDashboard.repaint();
    }//GEN-LAST:event_lblSettingsMouseClicked

    private void lblSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseEntered
        lblSettings.setBackground(new Color(69, 108, 123));
    }//GEN-LAST:event_lblSettingsMouseEntered

    private void lblReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseClicked
        if (lblReports.isEnabled()) {
            setPanelColour(pnlReports);
            resetPanelColour(pnlGRN, pnlSettings, pnlSupplier, pnlItem, pnlCashier);
            ReportPanel panel = new ReportPanel();
            this.pnlMiddle.removeAll();
            panel.setSize(pnlMiddle.getSize());
            pnlMiddle.add(panel);
            pnlMiddle.revalidate();
            pnlMiddle.repaint();

            this.pnlDashboard.removeAll();
            pnlDashboard.revalidate();
            pnlDashboard.repaint();
        } else {
            DialogFormAdminLogin adminLogin = new lk.ijse.wijithafc.view.DialogFormAdminLogin(this, true);
            adminLogin.setVisible(true);
            if (adminLogin.isLoged()) {
                enableFields("ADMIN");
                setPanelColour(pnlReports);
                resetPanelColour(pnlGRN, pnlSettings, pnlSupplier, pnlItem, pnlCashier);
                ReportPanel panel = new ReportPanel();
                this.pnlMiddle.removeAll();
                panel.setSize(pnlMiddle.getSize());
                pnlMiddle.add(panel);
                pnlMiddle.revalidate();
                pnlMiddle.repaint();
                this.pnlDashboard.removeAll();
                pnlDashboard.revalidate();
                pnlDashboard.repaint();
            }
        }
    }//GEN-LAST:event_lblReportsMouseClicked

    private void lblReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseEntered
        lblReports.setBackground(new Color(69, 108, 123));
    }//GEN-LAST:event_lblReportsMouseEntered

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        resetLabelColour(lblSettings);
        resetLabelColour(lblReports);
        resetLabelColour(lblGRN);
        resetLabelColour(lblSupplier);
        resetLabelColour(lblItem);
        resetLabelColour(lblCashier);

    }//GEN-LAST:event_jPanel10MouseEntered

    private void lblCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCancelMouseClicked

    private void lblCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseEntered
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/animalclinic/images/x-mark (3).png"));
        lblCancel.setIcon(icon);
    }//GEN-LAST:event_lblCancelMouseEntered

    private void lblCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseExited
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/animalclinic/images/x-mark (2).png"));
        lblCancel.setIcon(icon);
    }//GEN-LAST:event_lblCancelMouseExited

    private void lblCashierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierMouseEntered
        lblCashier.setBackground(new Color(69, 108, 123));
    }//GEN-LAST:event_lblCashierMouseEntered

    private void lblCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierMouseClicked
        setPanelColour(pnlCashier);
        resetPanelColour(pnlGRN, pnlSettings, pnlSupplier, pnlItem, pnlReports);
        setPanelColour(pnlCashier);
        resetPanelColour(pnlGRN, pnlSettings, pnlSupplier, pnlItem, pnlReports);
        CashierPanel cashierPanel = new CashierPanel();
        this.pnlMiddle.removeAll();
        cashierPanel.setSize(this.pnlMiddle.getSize());
        pnlMiddle.add(cashierPanel);
        pnlMiddle.revalidate();
        pnlMiddle.repaint();

        lk.ijse.wijithafc.view.panels.DashBoardCashier dashBoardCashier = new lk.ijse.wijithafc.view.panels.DashBoardCashier();
        this.pnlDashboard.removeAll();
        dashBoardCashier.setSize(this.pnlDashboard.getSize());
        pnlDashboard.add(dashBoardCashier);
        pnlDashboard.revalidate();
        pnlDashboard.repaint();
    }//GEN-LAST:event_lblCashierMouseClicked

    private void lblCashierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierMousePressed

    }//GEN-LAST:event_lblCashierMousePressed

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Do you need to Log out ?", "Attention", dialogButton);
        if (dialogButton == JOptionPane.YES_OPTION && isAdminLogged && userType.equals("USER")) {
            enableFields("USER");
        } else {
            this.dispose();
            LoginForm form = new LoginForm();
            form.setVisible(true);
        }

    }//GEN-LAST:event_lblLogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblCashier;
    private javax.swing.JLabel lblGRN;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblReports;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JPanel pnlCashier;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlGRN;
    private javax.swing.JPanel pnlItem;
    private static javax.swing.JPanel pnlMiddle;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JPanel pnlSettings;
    private javax.swing.JPanel pnlSupplier;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
 private void setPanelColour(JPanel panel) {
        panel.setBackground(new Color(69, 108, 123));
    }

    private void resetPanelColour(JPanel pnl1, JPanel pnl2, JPanel pnl3, JPanel pnl4, JPanel pnl5) {
        pnl1.setBackground(new Color(240, 240, 240));
        pnl2.setBackground(new Color(240, 240, 240));
        pnl3.setBackground(new Color(240, 240, 240));
        pnl4.setBackground(new Color(240, 240, 240));
        pnl5.setBackground(new Color(240, 240, 240));

    }

    private void setLabelColour(JLabel Label) {
        Label.setBackground(new Color(69, 108, 123));
    }

    private void resetLabelColour(JLabel Label) {
        Label.setBackground(new Color(0, 102, 102));
    }

    public static JPanel getMiddlePanel() {
        return pnlMiddle;
    }

    public static JFrame getMainFrame() {
        return homeFrame;
    }

    public void setLabelDisable() {
        lblGRN.setEnabled(false);
        lblItem.setEnabled(false);
        lblReports.setEnabled(false);
        lblSettings.setEnabled(false);
        lblSupplier.setEnabled(false);
    }

    public void setLabelEnable() {
        lblGRN.setEnabled(true);
        lblItem.setEnabled(true);
        lblReports.setEnabled(true);
        lblSettings.setEnabled(true);
        lblSupplier.setEnabled(true);
    }

    public static String getUserID() {
        return userID;
    }

    public static void setUserID(String userid) {
        userID = userid;
    }

    private void enableFields(String userType) {
        if (userType.equals("ADMIN")) {
            isAdminLogged = true;
            lblCashier.setEnabled(true);
            lblItem.setEnabled(true);
            lblSupplier.setEnabled(true);
            lblGRN.setEnabled(true);
            lblReports.setEnabled(true);
            lblSettings.setEnabled(true);
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/wijithafc/images/Admin.png"));
            lblAdmin.setIcon(icon);
            ImageIcon logout = new ImageIcon(this.getClass().getResource("/lk/ijse/wijithafc/images/logout2.png"));
            lblLogOut.setIcon(logout);
        } else {
            lblCashier.setEnabled(true);
            lblItem.setEnabled(false);
            lblSupplier.setEnabled(false);
            lblGRN.setEnabled(false);
            lblReports.setEnabled(false);
            lblSettings.setEnabled(false);
            lblAdmin.setIcon(null);
            ImageIcon logout = new ImageIcon(this.getClass().getResource("/lk/ijse/wijithafc/images/logout1.png"));
            lblLogOut.setIcon(logout);
            lblCashierMouseClicked(null);

        }
    }
}
